import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/autogenerated/": "structure",

  "/compare/": "structure",

  "/guides/": [
    "",
    "choosing-right-ai-model",
    "ai-model-pricing",
    "performance-benchmarks",
    {
      text: "Advanced Guides",
      icon: "graduation-cap",
      children: [
        "fine-tuning-guide",
        "prompt-engineering",
        "model-deployment",
      ],
    },
  ],
  
  "/research/": [
    "",
    "q1-2025-ai-performance",
    "evaluation-methods",
    {
      text: "Research Papers",
      icon: "file-alt",
      children: [
        "latest-papers",
        "benchmark-studies",
        "industry-reports",
      ],
    },
  ],
  
  "/tools/": [
    "",
    "comparison-calculator", 
    "cost-calculator",
    {
      text: "Interactive Tools",
      icon: "calculator",
      children: [
        "model-picker",
        "performance-analyzer",
        "roi-calculator",
      ],
    },
  ],
});