<template>
  <div class="autogenerated-index-layout">
    <!-- Header -->
    <header class="header">
      <div class="header-content">
        <div class="header-left">
          <a href="/" class="logo">
            <span class="logo-text">SNEOS</span>
          </a>
          <nav class="nav">
            <a href="https://sneos.com" class="nav-link">Home</a>
            <a href="https://sneos.com/about" class="nav-link">About</a>
            <a href="/compare/" class="nav-link active">AI Compare</a>
          </nav>
        </div>
        <div class="header-right">
          <button @click="toggleDarkMode" class="dark-mode-toggle" :title="isDarkMode ? 'Switch to light mode' : 'Switch to dark mode'">
            {{ isDarkMode ? '☀️' : '🌙' }}
          </button>
          <a href="https://share.sneos.com" class="nav-link">Share</a>
        </div>
      </div>
    </header>

    <!-- Main Content Area -->
    <div class="main-container">
      <!-- Sidebar -->
      <aside class="sidebar">
        <div class="sidebar-content">
          <h3 class="sidebar-title">Categories</h3>
          <div v-if="categories.length === 0" class="no-categories">
            Loading categories...
          </div>
          <nav class="category-nav" v-else>
            <div v-for="category in categories" :key="category.id" class="category-group">
              <button
                @click="toggleCategory(category.id)"
                class="category-link"
                :class="{ expanded: expandedCategories[category.id] }"
              >
                <span class="category-icon">{{ category.icon }}</span>
                <span class="category-name">{{ category.name }}</span>
                <span class="category-count">({{ getCategoryTotal(category) }})</span>
                <span class="category-toggle">{{ expandedCategories[category.id] ? '▼' : '▶' }}</span>
              </button>
              <div v-if="expandedCategories[category.id]" class="category-items">
                <!-- Direct items in category -->
                <a
                  v-for="item in category.items"
                  :key="item.path"
                  :href="item.path"
                  class="category-item"
                >
                  {{ item.title }}
                </a>
                <!-- Subcategories -->
                <div v-for="subcategory in category.subcategories" :key="subcategory.id" class="subcategory-group">
                  <button
                    @click="toggleSubcategory(category.id, subcategory.id)"
                    class="subcategory-link"
                    :class="{ expanded: expandedSubcategories[category.id + '-' + subcategory.id] }"
                  >
                    <span class="subcategory-name">{{ subcategory.name }}</span>
                    <span class="subcategory-count">({{ subcategory.items.length }})</span>
                    <span class="subcategory-toggle">{{ expandedSubcategories[category.id + '-' + subcategory.id] ? '▼' : '▶' }}</span>
                  </button>
                  <div v-if="expandedSubcategories[category.id + '-' + subcategory.id]" class="subcategory-items">
                    <a
                      v-for="item in subcategory.items"
                      :key="item.path"
                      :href="item.path"
                      class="subcategory-item"
                    >
                      {{ item.title }}
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </nav>

          <div class="sidebar-stats">
            <h4>Statistics</h4>
            <div class="stat-item">
              <span class="stat-label">Total Posts:</span>
              <span class="stat-value">{{ totalPosts }}</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Categories:</span>
              <span class="stat-value">{{ totalCategories }}</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Last Updated:</span>
              <span class="stat-value">{{ lastUpdated }}</span>
            </div>
          </div>
        </div>
      </aside>

      <!-- Content -->
      <main class="content">
        <div class="content-wrapper">
          <Content />
        </div>
      </main>
    </div>

    <!-- Footer -->
    <footer class="footer">
      <div class="footer-content">
        <div class="footer-brand">
          <h4>SNEOS</h4>
        </div>
        <div class="footer-links">
          <a href="https://sneos.com">Home</a>
          <a href="https://sneos.com">Sneos.com</a>
          <a href="https://sneos.com/blog">Blog</a>
        </div>
      </div>
      <div class="footer-bottom">
        <p>&copy; {{ currentYear }} SNEOS. All rights reserved.</p>
      </div>
    </footer>
  </div>
</template>

<script>
export default {
  name: 'AutogeneratedIndex',
  data() {
    return {
      isDarkMode: false,
      expandedCategories: {},
      expandedSubcategories: {}
    };
  },
  computed: {
    currentYear() {
      return new Date().getFullYear();
    },
    totalPosts() {
      if (this.$page.frontmatter.totalPosts) return this.$page.frontmatter.totalPosts;
      return this.categories.reduce((sum, cat) => {
        const directItems = cat.items?.length || 0;
        const subcategoryItems = cat.subcategories?.reduce((subSum, sub) => subSum + (sub.items?.length || 0), 0) || 0;
        return sum + directItems + subcategoryItems;
      }, 0);
    },
    totalCategories() {
      return this.$page.frontmatter.totalCategories || this.categories.length;
    },
    lastUpdated() {
      return this.$page.frontmatter.lastUpdatedDate || new Date().toLocaleDateString();
    },
    categories() {
      // Get all pages in ai-library directory
      const pages = (this.$site?.pages || []).filter(page =>
        page.path.startsWith('/ai-library/') &&
        page.path !== '/ai-library/' &&
        !page.path.endsWith('/ai-library/index.html')
      );

      const categoryMap = {};

      // Organize pages by category
      pages.forEach(page => {
        const pathParts = page.path.replace(/^\/ai-library\//, '').split('/').filter(p => p);

        if (pathParts.length >= 1) {
          const categorySlug = pathParts[0];

          if (!categoryMap[categorySlug]) {
            const categoryName = categorySlug
              .split('-')
              .map(word => word.charAt(0).toUpperCase() + word.slice(1))
              .join(' ');

            let icon = '📝';
            const lowerName = categoryName.toLowerCase();
            if (lowerName.includes('finance') || lowerName.includes('investment')) icon = '💰';
            else if (lowerName.includes('law') || lowerName.includes('legal')) icon = '⚖️';
            else if (lowerName.includes('education') || lowerName.includes('learning')) icon = '🎓';
            else if (lowerName.includes('tech') || lowerName.includes('programming')) icon = '💻';
            else if (lowerName.includes('ai') || lowerName.includes('comparison')) icon = '🤖';
            else if (lowerName.includes('health') || lowerName.includes('medical') || lowerName.includes('wellness')) icon = '🏥';
            else if (lowerName.includes('science') || lowerName.includes('research')) icon = '🔬';
            else if (lowerName.includes('art') || lowerName.includes('creative')) icon = '🎨';
            else if (lowerName.includes('design')) icon = '✨';
            else if (lowerName.includes('business') || lowerName.includes('entrepreneur')) icon = '💼';
            else if (lowerName.includes('marketing') || lowerName.includes('seo')) icon = '📈';
            else if (lowerName.includes('environment') || lowerName.includes('sustainability')) icon = '🌱';
            else if (lowerName.includes('food') || lowerName.includes('cooking')) icon = '🍳';
            else if (lowerName.includes('travel')) icon = '✈️';
            else if (lowerName.includes('sport') || lowerName.includes('fitness')) icon = '⚽';
            else if (lowerName.includes('fashion') || lowerName.includes('beauty')) icon = '👗';
            else if (lowerName.includes('crypto') || lowerName.includes('blockchain')) icon = '₿';
            else if (lowerName.includes('security') || lowerName.includes('privacy')) icon = '🔒';
            else if (lowerName.includes('data') || lowerName.includes('analytics')) icon = '📊';
            else if (lowerName.includes('automotive') || lowerName.includes('vehicle')) icon = '🚗';
            else if (lowerName.includes('real estate') || lowerName.includes('property')) icon = '🏠';
            else if (lowerName.includes('gaming') || lowerName.includes('esport')) icon = '🎮';
            else if (lowerName.includes('music')) icon = '🎵';
            else if (lowerName.includes('pet')) icon = '🐾';
            else if (lowerName.includes('parent') || lowerName.includes('child')) icon = '👶';
            else if (lowerName.includes('home') || lowerName.includes('diy')) icon = '🏡';
            else if (lowerName.includes('personal') || lowerName.includes('productivity')) icon = '📋';

            categoryMap[categorySlug] = {
              id: categorySlug,
              name: categoryName,
              icon: icon,
              items: [],
              subcategories: {}
            };
          }

          // Add subcategory if exists
          if (pathParts.length >= 2) {
            const subcategorySlug = pathParts[1];

            if (!categoryMap[categorySlug].subcategories[subcategorySlug]) {
              const subcategoryName = subcategorySlug
                .split('-')
                .map(word => word.charAt(0).toUpperCase() + word.slice(1))
                .join(' ');

              categoryMap[categorySlug].subcategories[subcategorySlug] = {
                id: subcategorySlug,
                name: subcategoryName,
                items: []
              };
            }

            categoryMap[categorySlug].subcategories[subcategorySlug].items.push({
              title: page.title || page.path.split('/').pop().replace('.html', ''),
              path: page.path
            });
          } else {
            categoryMap[categorySlug].items.push({
              title: page.title || page.path.split('/').pop().replace('.html', ''),
              path: page.path
            });
          }
        }
      });

      // Convert to array and sort
      return Object.values(categoryMap)
        .filter(cat => cat.items.length > 0 || Object.keys(cat.subcategories).length > 0)
        .sort((a, b) => {
          const aTotal = a.items.length + Object.values(a.subcategories).reduce((sum, sub) => sum + sub.items.length, 0);
          const bTotal = b.items.length + Object.values(b.subcategories).reduce((sum, sub) => sum + sub.items.length, 0);
          return bTotal - aTotal;
        })
        .map(cat => ({
          ...cat,
          subcategories: Object.values(cat.subcategories).sort((a, b) => b.items.length - a.items.length)
        }));
    }
  },
  mounted() {
    // Check for saved dark mode preference or system preference
    const savedTheme = localStorage.getItem('darkMode');
    if (savedTheme) {
      this.isDarkMode = savedTheme === 'true';
    } else {
      this.isDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;
    }
    this.applyTheme();

    // Listen for system theme changes
    window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', (e) => {
      if (!localStorage.getItem('darkMode')) {
        this.isDarkMode = e.matches;
        this.applyTheme();
      }
    });

    // Debug: Log categories to console
    console.log('Categories loaded:', this.categories);
    console.log('Total pages:', this.$site?.pages?.length);
    console.log('AI Library pages:', this.$site?.pages?.filter(p => p.path.startsWith('/ai-library/')).length);
  },
  methods: {
    getCategoryTotal(category) {
      const directItems = category.items?.length || 0;
      const subcategoryItems = category.subcategories?.reduce((sum, sub) => sum + (sub.items?.length || 0), 0) || 0;
      return directItems + subcategoryItems;
    },
    toggleCategory(categoryId) {
      this.expandedCategories[categoryId] = !this.expandedCategories[categoryId];
      this.$forceUpdate();
    },
    toggleSubcategory(categoryId, subcategoryId) {
      const key = categoryId + '-' + subcategoryId;
      this.expandedSubcategories[key] = !this.expandedSubcategories[key];
      this.$forceUpdate();
    },
    scrollToCategory(categoryId) {
      const element = document.getElementById(categoryId);
      if (element) {
        element.scrollIntoView({ behavior: 'smooth' });
      }
    },
    toggleDarkMode() {
      this.isDarkMode = !this.isDarkMode;
      localStorage.setItem('darkMode', this.isDarkMode.toString());
      this.applyTheme();
    },
    applyTheme() {
      if (this.isDarkMode) {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
    }
  }
};
</script>

<style scoped>
/* CSS Custom Properties for Theme Support */
:root {
  --bg-primary: #ffffff;
  --bg-secondary: #f8f9fa;
  --bg-tertiary: #ffffff;
  --text-primary: #2c3e50;
  --text-secondary: #666666;
  --text-muted: #95a5a6;
  --border-color: #e1e5e9;
  --shadow: rgba(0,0,0,0.1);
  --accent-primary: #667eea;
  --accent-secondary: #764ba2;
  --header-bg: #ffffff;
  --footer-bg: #2c3e50;
  --footer-text: #ffffff;
  --footer-link: #bdc3c7;
  --sidebar-bg: #f8f9fa;
}

:root.dark {
  --bg-primary: #1a1a1a;
  --bg-secondary: #2d2d2d;
  --bg-tertiary: #363636;
  --text-primary: #e1e1e1;
  --text-secondary: #b8b8b8;
  --text-muted: #888888;
  --border-color: #404040;
  --shadow: rgba(0,0,0,0.3);
  --accent-primary: #8a9aff;
  --accent-secondary: #9575cd;
  --header-bg: #1f1f1f;
  --footer-bg: #151515;
  --footer-text: #e1e1e1;
  --footer-link: #b8b8b8;
  --sidebar-bg: #2d2d2d;
}

.autogenerated-index-layout {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background-color: var(--bg-primary);
  color: var(--text-primary);
  transition: background-color 0.3s ease, color 0.3s ease;
}

/* Header Styles */
.header {
  background: var(--header-bg);
  border-bottom: 1px solid var(--border-color);
  position: sticky;
  top: 0;
  z-index: 100;
  box-shadow: 0 2px 4px var(--shadow);
  transition: background-color 0.3s ease, border-color 0.3s ease;
}

.header-content {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  height: 60px;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 30px;
}

.logo {
  text-decoration: none;
  font-weight: bold;
  font-size: 24px;
  color: var(--text-primary);
  transition: color 0.3s ease;
}

.logo-text {
  background: linear-gradient(135deg, var(--accent-primary) 0%, var(--accent-secondary) 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.dark-mode-toggle {
  background: none;
  border: 1px solid var(--border-color);
  border-radius: 6px;
  padding: 8px 12px;
  cursor: pointer;
  font-size: 16px;
  margin-right: 15px;
  transition: all 0.3s ease;
  background-color: var(--bg-secondary);
}

.dark-mode-toggle:hover {
  background-color: var(--bg-tertiary);
  transform: scale(1.05);
}

.nav {
  display: flex;
  gap: 20px;
}

.nav-link {
  text-decoration: none;
  color: var(--text-secondary);
  font-weight: 500;
  padding: 8px 12px;
  border-radius: 6px;
  transition: all 0.3s ease;
}

.nav-link:hover, .nav-link.active {
  color: var(--accent-primary);
  background: var(--bg-secondary);
}

/* Main Container */
.main-container {
  flex: 1;
  display: flex;
  max-width: 1200px;
  margin: 0 auto;
  width: 100%;
}

/* Sidebar Styles */
.sidebar {
  width: 280px;
  background: var(--sidebar-bg);
  border-right: 1px solid var(--border-color);
  padding: 20px 0;
  transition: background-color 0.3s ease, border-color 0.3s ease;
}

.sidebar-content {
  padding: 0 20px;
  position: sticky;
  top: 80px;
}

.sidebar-title {
  font-size: 18px;
  font-weight: 600;
  color: var(--text-primary);
  margin-bottom: 15px;
  padding-bottom: 10px;
  border-bottom: 2px solid var(--accent-primary);
  transition: color 0.3s ease, border-color 0.3s ease;
}

.category-nav {
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin-bottom: 30px;
}

.category-group {
  margin-bottom: 4px;
}

.category-link {
  width: 100%;
  text-align: left;
  background: none;
  border: none;
  color: var(--text-secondary);
  padding: 10px 15px;
  border-radius: 8px;
  transition: all 0.3s ease;
  font-weight: 500;
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  font-size: 14px;
}

.category-link:hover {
  background: var(--bg-tertiary);
  color: var(--accent-primary);
  box-shadow: 0 2px 8px var(--shadow);
}

.category-link.expanded {
  background: var(--bg-tertiary);
  color: var(--accent-primary);
}

.category-icon {
  flex-shrink: 0;
  font-size: 16px;
}

.category-name {
  flex: 1;
}

.category-toggle {
  flex-shrink: 0;
  font-size: 10px;
  transition: transform 0.3s ease;
}

.category-items {
  padding-left: 35px;
  margin-top: 4px;
  margin-bottom: 8px;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.category-item {
  text-decoration: none;
  color: var(--text-muted);
  padding: 6px 12px;
  border-radius: 6px;
  font-size: 13px;
  transition: all 0.2s ease;
  display: block;
}

.category-item:hover {
  background: var(--bg-tertiary);
  color: var(--accent-primary);
  padding-left: 16px;
}

.category-count {
  font-size: 11px;
  color: var(--text-muted);
  margin-left: 4px;
}

.subcategory-group {
  margin-top: 4px;
  margin-bottom: 4px;
}

.subcategory-link {
  width: 100%;
  text-align: left;
  background: none;
  border: none;
  color: var(--text-secondary);
  padding: 8px 12px;
  border-radius: 6px;
  transition: all 0.2s ease;
  font-weight: 500;
  display: flex;
  align-items: center;
  gap: 6px;
  cursor: pointer;
  font-size: 13px;
  margin-left: 10px;
}

.subcategory-link:hover {
  background: var(--bg-tertiary);
  color: var(--accent-primary);
}

.subcategory-link.expanded {
  background: var(--bg-tertiary);
  color: var(--accent-primary);
}

.subcategory-name {
  flex: 1;
}

.subcategory-count {
  font-size: 10px;
  color: var(--text-muted);
}

.subcategory-toggle {
  flex-shrink: 0;
  font-size: 9px;
  transition: transform 0.3s ease;
}

.subcategory-items {
  padding-left: 20px;
  margin-top: 2px;
  margin-bottom: 4px;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.subcategory-item {
  text-decoration: none;
  color: var(--text-muted);
  padding: 5px 10px;
  border-radius: 4px;
  font-size: 12px;
  transition: all 0.2s ease;
  display: block;
}

.subcategory-item:hover {
  background: var(--bg-tertiary);
  color: var(--accent-primary);
  padding-left: 14px;
}

.sidebar-stats {
  background: var(--bg-tertiary);
  padding: 20px;
  border-radius: 10px;
  box-shadow: 0 2px 10px var(--shadow);
  transition: background-color 0.3s ease;
}

.sidebar-stats h4 {
  margin: 0 0 15px 0;
  color: var(--text-primary);
  font-size: 16px;
  transition: color 0.3s ease;
}

.stat-item {
  display: flex;
  justify-content: space-between;
  margin-bottom: 8px;
  font-size: 14px;
}

.stat-label {
  color: var(--text-secondary);
  transition: color 0.3s ease;
}

.stat-value {
  font-weight: 600;
  color: var(--text-primary);
  transition: color 0.3s ease;
}

.no-categories {
  padding: 20px;
  text-align: center;
  color: var(--text-muted);
  font-style: italic;
}

/* Content Styles */
.content {
  flex: 1;
  padding: 20px 40px;
}

.content-wrapper {
  max-width: 800px;
}

/* Footer Styles */
.footer {
  background: var(--footer-bg);
  color: var(--footer-text);
  margin-top: auto;
  transition: background-color 0.3s ease, color 0.3s ease;
}

.footer-content {
  max-width: 1200px;
  margin: 0 auto;
  padding: 30px 20px 15px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 20px;
}

.footer-brand h4 {
  margin: 0;
  color: var(--footer-text);
  font-size: 18px;
  font-weight: 600;
  transition: color 0.3s ease;
}

.footer-links {
  display: flex;
  gap: 25px;
  align-items: center;
}

.footer-links a {
  color: var(--footer-link);
  text-decoration: none;
  transition: color 0.3s ease;
  font-size: 14px;
}

.footer-links a:hover {
  color: var(--footer-text);
}

.footer-bottom {
  border-top: 1px solid var(--border-color);
  padding: 15px 20px;
  text-align: center;
  color: var(--text-muted);
  font-size: 13px;
  transition: border-color 0.3s ease, color 0.3s ease;
}

.footer-bottom p {
  margin: 0;
}

/* Responsive Design */
@media (max-width: 768px) {
  .main-container {
    flex-direction: column;
  }

  .sidebar {
    width: 100%;
    order: 2;
  }

  .content {
    padding: 20px;
    order: 1;
  }

  .header-content {
    padding: 0 15px;
  }

  .nav {
    display: none;
  }

  .footer-content {
    flex-direction: column;
    align-items: center;
    gap: 15px;
    padding: 20px 15px 10px;
  }

  .footer-links {
    gap: 15px;
  }
}

@media (max-width: 480px) {
  .footer-links {
    flex-direction: column;
    gap: 10px;
  }
}
</style>