<template>
  <div class="autogenerated-index-layout">
    <!-- Header -->
    <header class="header">
      <div class="header-content">
        <div class="header-left">
          <a href="/" class="logo">
            <span class="logo-text">SNEOS</span>
          </a>
          <nav class="nav">
            <a href="https://sneos.com" class="nav-link">Home</a>
            <a href="https://sneos.com/about" class="nav-link">About</a>
            <a href="/compare/" class="nav-link active">AI Compare</a>
          </nav>
        </div>
        <div class="header-right">
          <button @click="toggleDarkMode" class="dark-mode-toggle" :title="isDarkMode ? 'Switch to light mode' : 'Switch to dark mode'">
            {{ isDarkMode ? '☀️' : '🌙' }}
          </button>
          <a href="https://share.sneos.com" class="nav-link">Share</a>
        </div>
      </div>
    </header>

    <!-- Main Content Area -->
    <div class="main-container">
      <!-- Sidebar -->
      <aside class="sidebar">
        <div class="sidebar-content">
          <h3 class="sidebar-title">Categories</h3>
          <nav class="category-nav">
            <div v-for="category in categories" :key="category.id" class="category-group">
              <button
                @click="toggleCategory(category.id)"
                class="category-link"
                :class="{ expanded: expandedCategories[category.id] }"
              >
                <span class="category-icon">{{ category.icon }}</span>
                <span class="category-name">{{ category.name }}</span>
                <span class="category-toggle">{{ expandedCategories[category.id] ? '▼' : '▶' }}</span>
              </button>
              <div v-if="expandedCategories[category.id]" class="category-items">
                <a
                  v-for="item in category.items"
                  :key="item.path"
                  :href="item.path"
                  class="category-item"
                >
                  {{ item.title }}
                </a>
              </div>
            </div>
          </nav>

          <div class="sidebar-stats">
            <h4>Statistics</h4>
            <div class="stat-item">
              <span class="stat-label">Total Posts:</span>
              <span class="stat-value">{{ totalPosts }}</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Categories:</span>
              <span class="stat-value">{{ totalCategories }}</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Last Updated:</span>
              <span class="stat-value">{{ lastUpdated }}</span>
            </div>
          </div>
        </div>
      </aside>

      <!-- Content -->
      <main class="content">
        <div class="content-wrapper">
          <Content />
        </div>
      </main>
    </div>

    <!-- Footer -->
    <footer class="footer">
      <div class="footer-content">
        <div class="footer-section">
          <h4>SNEOS</h4>
          <ul>
            <li><a href="https://sneos.com">Home</a></li>
            <li><a href="https://sneos.com/about">About</a></li>
            <li><a href="https://sneos.com/contact">Contact</a></li>
          </ul>
        </div>
        <div class="footer-section">
          <h4>AI Tools</h4>
          <ul>
            <li><a href="/compare/">AI Comparison</a></li>
            <li><a href="https://share.sneos.com">Share Platform</a></li>
            <li><a href="https://sneos.com/tools">AI Tools</a></li>
          </ul>
        </div>
        <div class="footer-section">
          <h4>Resources</h4>
          <ul>
            <li><a href="https://sneos.com/blog">Blog</a></li>
            <li><a href="https://sneos.com/docs">Documentation</a></li>
            <li><a href="https://sneos.com/api">API</a></li>
          </ul>
        </div>
        <div class="footer-section">
          <h4>Connect</h4>
          <ul>
            <li><a href="https://twitter.com/sneos">Twitter</a></li>
            <li><a href="https://github.com/sneos">GitHub</a></li>
            <li><a href="https://linkedin.com/company/sneos">LinkedIn</a></li>
          </ul>
        </div>
      </div>
      <div class="footer-bottom">
        <p>&copy; {{ currentYear }} SNEOS. All rights reserved. | Powered by AI Automation</p>
      </div>
    </footer>
  </div>
</template>

<script>
export default {
  name: 'AutogeneratedIndex',
  data() {
    return {
      isDarkMode: false,
      expandedCategories: {}
    };
  },
  computed: {
    currentYear() {
      return new Date().getFullYear();
    },
    totalPosts() {
      // This would be dynamically calculated based on the actual content
      return this.$page.frontmatter.totalPosts || 120;
    },
    totalCategories() {
      return this.$page.frontmatter.totalCategories || 8;
    },
    lastUpdated() {
      return this.$page.frontmatter.lastUpdated || new Date().toLocaleDateString();
    },
    categories() {
      // Get all pages and organize by category
      const pages = (this.$site?.pages || []).filter(page =>
        page.path.includes('/compare/') &&
        page.path !== '/compare/' &&
        !page.path.includes('/compare/autogenerated/index')
      );

      const categoryMap = {
        finance: { id: 'finance', name: 'Finance', icon: '💰', items: [] },
        law: { id: 'law', name: 'Law', icon: '⚖️', items: [] },
        research: { id: 'research', name: 'Research', icon: '🔬', items: [] },
        education: { id: 'education', name: 'Education', icon: '🎓', items: [] },
        technology: { id: 'technology', name: 'Technology', icon: '💻', items: [] },
        ai: { id: 'ai', name: 'AI & Future', icon: '🤖', items: [] },
        lifestyle: { id: 'lifestyle', name: 'Lifestyle', icon: '🌟', items: [] },
        other: { id: 'other', name: 'Other', icon: '📝', items: [] }
      };

      // Categorize pages based on title/tags
      pages.forEach(page => {
        const title = page.title || '';
        const titleLower = title.toLowerCase();
        const item = { title: page.title, path: page.path };

        if (titleLower.includes('finance') || titleLower.includes('investment') ||
            titleLower.includes('stock') || titleLower.includes('retirement') ||
            titleLower.includes('tax') || titleLower.includes('credit')) {
          categoryMap.finance.items.push(item);
        } else if (titleLower.includes('law') || titleLower.includes('legal') ||
                   titleLower.includes('court') || titleLower.includes('lawyer')) {
          categoryMap.law.items.push(item);
        } else if (titleLower.includes('research') || titleLower.includes('medical') ||
                   titleLower.includes('science') || titleLower.includes('brain')) {
          categoryMap.research.items.push(item);
        } else if (titleLower.includes('education') || titleLower.includes('learning') ||
                   titleLower.includes('student') || titleLower.includes('university')) {
          categoryMap.education.items.push(item);
        } else if (titleLower.includes('technology') || titleLower.includes('tech') ||
                   titleLower.includes('quantum') || titleLower.includes('space')) {
          categoryMap.technology.items.push(item);
        } else if (titleLower.includes('ai') || titleLower.includes('artificial intelligence') ||
                   titleLower.includes('future')) {
          categoryMap.ai.items.push(item);
        } else if (titleLower.includes('life') || titleLower.includes('health') ||
                   titleLower.includes('relationship') || titleLower.includes('career')) {
          categoryMap.lifestyle.items.push(item);
        } else {
          categoryMap.other.items.push(item);
        }
      });

      // Return only categories with items, sorted by item count
      return Object.values(categoryMap)
        .filter(cat => cat.items.length > 0)
        .sort((a, b) => b.items.length - a.items.length);
    }
  },
  mounted() {
    // Check for saved dark mode preference or system preference
    const savedTheme = localStorage.getItem('darkMode');
    if (savedTheme) {
      this.isDarkMode = savedTheme === 'true';
    } else {
      this.isDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;
    }
    this.applyTheme();

    // Listen for system theme changes
    window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', (e) => {
      if (!localStorage.getItem('darkMode')) {
        this.isDarkMode = e.matches;
        this.applyTheme();
      }
    });
  },
  methods: {
    toggleCategory(categoryId) {
      this.expandedCategories[categoryId] = !this.expandedCategories[categoryId];
      this.$forceUpdate(); // Force update to reflect changes
    },
    scrollToCategory(categoryId) {
      const element = document.getElementById(categoryId);
      if (element) {
        element.scrollIntoView({ behavior: 'smooth' });
      }
    },
    toggleDarkMode() {
      this.isDarkMode = !this.isDarkMode;
      localStorage.setItem('darkMode', this.isDarkMode.toString());
      this.applyTheme();
    },
    applyTheme() {
      if (this.isDarkMode) {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
      }
    }
  }
};
</script>

<style scoped>
/* CSS Custom Properties for Theme Support */
:root {
  --bg-primary: #ffffff;
  --bg-secondary: #f8f9fa;
  --bg-tertiary: #ffffff;
  --text-primary: #2c3e50;
  --text-secondary: #666666;
  --text-muted: #95a5a6;
  --border-color: #e1e5e9;
  --shadow: rgba(0,0,0,0.1);
  --accent-primary: #667eea;
  --accent-secondary: #764ba2;
  --header-bg: #ffffff;
  --footer-bg: #2c3e50;
  --footer-text: #ffffff;
  --footer-link: #bdc3c7;
  --sidebar-bg: #f8f9fa;
}

:root.dark {
  --bg-primary: #1a1a1a;
  --bg-secondary: #2d2d2d;
  --bg-tertiary: #363636;
  --text-primary: #e1e1e1;
  --text-secondary: #b8b8b8;
  --text-muted: #888888;
  --border-color: #404040;
  --shadow: rgba(0,0,0,0.3);
  --accent-primary: #8a9aff;
  --accent-secondary: #9575cd;
  --header-bg: #1f1f1f;
  --footer-bg: #151515;
  --footer-text: #e1e1e1;
  --footer-link: #b8b8b8;
  --sidebar-bg: #2d2d2d;
}

.autogenerated-index-layout {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background-color: var(--bg-primary);
  color: var(--text-primary);
  transition: background-color 0.3s ease, color 0.3s ease;
}

/* Header Styles */
.header {
  background: var(--header-bg);
  border-bottom: 1px solid var(--border-color);
  position: sticky;
  top: 0;
  z-index: 100;
  box-shadow: 0 2px 4px var(--shadow);
  transition: background-color 0.3s ease, border-color 0.3s ease;
}

.header-content {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  height: 60px;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 30px;
}

.logo {
  text-decoration: none;
  font-weight: bold;
  font-size: 24px;
  color: var(--text-primary);
  transition: color 0.3s ease;
}

.logo-text {
  background: linear-gradient(135deg, var(--accent-primary) 0%, var(--accent-secondary) 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.dark-mode-toggle {
  background: none;
  border: 1px solid var(--border-color);
  border-radius: 6px;
  padding: 8px 12px;
  cursor: pointer;
  font-size: 16px;
  margin-right: 15px;
  transition: all 0.3s ease;
  background-color: var(--bg-secondary);
}

.dark-mode-toggle:hover {
  background-color: var(--bg-tertiary);
  transform: scale(1.05);
}

.nav {
  display: flex;
  gap: 20px;
}

.nav-link {
  text-decoration: none;
  color: var(--text-secondary);
  font-weight: 500;
  padding: 8px 12px;
  border-radius: 6px;
  transition: all 0.3s ease;
}

.nav-link:hover, .nav-link.active {
  color: var(--accent-primary);
  background: var(--bg-secondary);
}

/* Main Container */
.main-container {
  flex: 1;
  display: flex;
  max-width: 1200px;
  margin: 0 auto;
  width: 100%;
}

/* Sidebar Styles */
.sidebar {
  width: 280px;
  background: var(--sidebar-bg);
  border-right: 1px solid var(--border-color);
  padding: 20px 0;
  transition: background-color 0.3s ease, border-color 0.3s ease;
}

.sidebar-content {
  padding: 0 20px;
  position: sticky;
  top: 80px;
}

.sidebar-title {
  font-size: 18px;
  font-weight: 600;
  color: var(--text-primary);
  margin-bottom: 15px;
  padding-bottom: 10px;
  border-bottom: 2px solid var(--accent-primary);
  transition: color 0.3s ease, border-color 0.3s ease;
}

.category-nav {
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin-bottom: 30px;
}

.category-group {
  margin-bottom: 4px;
}

.category-link {
  width: 100%;
  text-align: left;
  background: none;
  border: none;
  color: var(--text-secondary);
  padding: 10px 15px;
  border-radius: 8px;
  transition: all 0.3s ease;
  font-weight: 500;
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  font-size: 14px;
}

.category-link:hover {
  background: var(--bg-tertiary);
  color: var(--accent-primary);
  box-shadow: 0 2px 8px var(--shadow);
}

.category-link.expanded {
  background: var(--bg-tertiary);
  color: var(--accent-primary);
}

.category-icon {
  flex-shrink: 0;
  font-size: 16px;
}

.category-name {
  flex: 1;
}

.category-toggle {
  flex-shrink: 0;
  font-size: 10px;
  transition: transform 0.3s ease;
}

.category-items {
  padding-left: 35px;
  margin-top: 4px;
  margin-bottom: 8px;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.category-item {
  text-decoration: none;
  color: var(--text-muted);
  padding: 6px 12px;
  border-radius: 6px;
  font-size: 13px;
  transition: all 0.2s ease;
  display: block;
}

.category-item:hover {
  background: var(--bg-tertiary);
  color: var(--accent-primary);
  padding-left: 16px;
}

.sidebar-stats {
  background: var(--bg-tertiary);
  padding: 20px;
  border-radius: 10px;
  box-shadow: 0 2px 10px var(--shadow);
  transition: background-color 0.3s ease;
}

.sidebar-stats h4 {
  margin: 0 0 15px 0;
  color: var(--text-primary);
  font-size: 16px;
  transition: color 0.3s ease;
}

.stat-item {
  display: flex;
  justify-content: space-between;
  margin-bottom: 8px;
  font-size: 14px;
}

.stat-label {
  color: var(--text-secondary);
  transition: color 0.3s ease;
}

.stat-value {
  font-weight: 600;
  color: var(--text-primary);
  transition: color 0.3s ease;
}

/* Content Styles */
.content {
  flex: 1;
  padding: 20px 40px;
}

.content-wrapper {
  max-width: 800px;
}

/* Footer Styles */
.footer {
  background: var(--footer-bg);
  color: var(--footer-text);
  margin-top: auto;
  transition: background-color 0.3s ease, color 0.3s ease;
}

.footer-content {
  max-width: 1200px;
  margin: 0 auto;
  padding: 40px 20px 20px;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 30px;
}

.footer-section h4 {
  margin-bottom: 15px;
  color: var(--footer-text);
  font-size: 16px;
  transition: color 0.3s ease;
}

.footer-section ul {
  list-style: none;
  padding: 0;
  margin: 0;
}

.footer-section li {
  margin-bottom: 8px;
}

.footer-section a {
  color: var(--footer-link);
  text-decoration: none;
  transition: color 0.3s ease;
}

.footer-section a:hover {
  color: var(--footer-text);
}

.footer-bottom {
  border-top: 1px solid var(--border-color);
  padding: 20px;
  text-align: center;
  color: var(--text-muted);
  font-size: 14px;
  transition: border-color 0.3s ease, color 0.3s ease;
}

/* Responsive Design */
@media (max-width: 768px) {
  .main-container {
    flex-direction: column;
  }

  .sidebar {
    width: 100%;
    order: 2;
  }

  .content {
    padding: 20px;
    order: 1;
  }

  .header-content {
    padding: 0 15px;
  }

  .nav {
    display: none;
  }

  .footer-content {
    grid-template-columns: repeat(2, 1fr);
    gap: 20px;
    padding: 30px 15px 15px;
  }
}

@media (max-width: 480px) {
  .footer-content {
    grid-template-columns: 1fr;
  }
}
</style>